ishioni/homelab-ops

cluster/flux/flux-system/flux-cluster.yaml
Pivot to new repo with new name
**Benefits**
- fixes #
=> feat: pivot to new repo

cluster/core/kube-system/kube-vip/daemon-set.yaml, cluster/flux/flux-system/flux-cluster.yaml, tmpl/ansible/kube-vip.yml, tmpl/cluster/cluster-settings.yaml, tmpl/cluster/flux-cluster.yaml, tmpl/cluster/flux-system/kustomization.yaml, tmpl/cluster/flux-system/webhooks/github/ingress.yaml, tmpl/cluster/flux-system/webhooks/github/kustomization.yaml, tmpl/cluster/flux-system/webhooks/github/receiver.yaml, tmpl/cluster/flux-system/webhooks/github/secret.sops.yaml, tmpl/cluster/flux-system/webhooks/kustomization.yaml, tmpl/cluster/kube-vip-daemonset.yaml
Sync tmpl folder with upstream
**Benefits**
- fixes #
=> feat: upstream templates

cluster/apps/system-upgrade/system-upgrade-controller/agent-plan.yaml, cluster/apps/system-upgrade/system-upgrade-controller/server-plan.yaml, provision/ansible/inventory/group_vars/kubernetes/k3s.yml
Update to 1.24
**Benefits**
- fixes #
=> Bump k3s to 1.24

cluster/config/cluster-secrets.sops.yaml, cluster/core/cert-manager/cert-manager-secret.sops.yaml, cluster/core/cert-manager/kustomization.yaml, cluster/core/cert-manager/letsencrypt-production.yaml, cluster/core/cert-manager/letsencrypt-staging.yaml
Use cloudflare and dns-01 for cert-manager
=> feat: use cloudflare in cert-manager

cluster/charts/external-dns-charts.yaml, cluster/charts/kustomization.yaml, cluster/core/external-dns/external-dns-secret.sops.yaml, cluster/core/external-dns/helm-release.yaml, cluster/core/external-dns/kustomization.yaml, cluster/core/kustomization.yaml, cluster/core/namespaces/external-dns.yaml, cluster/core/namespaces/kustomization.yaml
So that we can get rid off of the wildcard CNAME
**Benefits**
- fixes #
=> feat: add external-dns

cluster/core/external-dns/external-dns-secret.sops.yaml
=> feat: external-dns v2

cluster/core/external-dns/external-dns-secret.sops.yaml, cluster/core/external-dns/helm-release.yaml
=> fix: external-dns api token

cluster/apps/default/hajimari/helm-release.yaml, cluster/apps/flux-system/webhooks/github/ingress.yaml, cluster/apps/media/prowlarr/helm-release.yaml, cluster/apps/media/radarr/helm-release.yaml, cluster/apps/media/readarr/helm-release.yaml, cluster/apps/media/sonarr/helm-release.yaml, cluster/apps/media/transmission/helm-release.yaml, cluster/apps/minecraft/helm-release.yaml, cluster/apps/nextcloud/helm-release.yaml, cluster/apps/reverse-proxy/helm-release.yaml
Most of these actually shouldn't be public, but will have to be for now until we get split-brain DNS working and a second ingress controller for them
**Benefits**
- fixes #
=> feat: handle ingressess with external-dns

terraform/cloudflare/main.tf
We don't need this anymore
**Benefits**
- fixes #
=> feat: remove wildcard cname

cluster/core/kustomization.yaml
=> fix: delete dangling kustomizations

cluster/apps/default/hajimari/helm-release.yaml, cluster/apps/reverse-proxy/helm-release.yaml
Switch internal services to private ingress
**Benefits**
- fixes #20
=> feat: switch private services to private ingress

terraform/cloudflare/main.tf
=> fix: use remote backend for terraform

cluster/apps/nextcloud/config-pvc.yaml, cluster/apps/nextcloud/helm-release.yaml, cluster/config/cluster-secrets.sops.yaml, terraform/minio/.terraform.lock.hcl, terraform/minio/main.tf, terraform/minio/nextcloud.tf, terraform/minio/secret.sops.yaml
Use object storage as the data backend for nextcloud
**Benefits**
No more nasty big PVCs
A bit slower?
=> feat: nextcloud s3

cluster/apps/minecraft/helm-release.yaml
=> chore: bump minecraft to 1.19.2

cluster/apps/media/prowlarr/helm-release.yaml, cluster/apps/media/radarr/helm-release.yaml, cluster/apps/media/readarr/helm-release.yaml, cluster/apps/media/sonarr/helm-release.yaml, cluster/apps/media/transmission/helm-release.yaml
=> fix: media apps teplates v2

cluster/core/networking/ingress-private/helm-release.yaml, cluster/core/networking/ingress-public/helm-release.yaml
Adds pretty error pages to nginx
**Benefits**
Pretty
=> feat: add pretty error pages

cluster/charts/kustomization.yaml, cluster/charts/vmware-tanzu-charts.yaml, cluster/config/cluster-secrets.sops.yaml, cluster/core/storage/velero/helm-release.yaml, cluster/core/storage/velero/kustomization.yaml, cluster/crds/velero/crds.yaml, cluster/crds/velero/kustomization.yaml, terraform/minio/nextcloud.tf, terraform/minio/secret.sops.yaml, terraform/minio/velero.tf
Fixes #5 
**Benefits**
Backups!
- fixes #
=> feat: Velero

cluster/apps/media/radarr/helm-release.yaml, cluster/apps/media/readarr/helm-release.yaml, cluster/apps/media/sonarr/helm-release.yaml, cluster/apps/media/transmission/helm-release.yaml, cluster/core/storage/velero/helm-release.yaml
Switch velero to backup pvcs by default
**Benefits**
- fixes #
=> feat: enable restic backups by default

cluster/apps/media/prowlarr/helm-release.yaml, cluster/apps/media/radarr/helm-release.yaml, cluster/apps/media/readarr/helm-release.yaml, cluster/apps/media/sonarr/helm-release.yaml, cluster/apps/media/transmission/helm-release.yaml, cluster/apps/minecraft/helm-release.yaml, cluster/apps/nextcloud/helm-release.yaml, cluster/core/storage/velero/helm-release.yaml
It doesn't work as well as I thought it would
=> feat: don't use restic for everything by default

cluster/core/networking/ingress-private/helm-release.yaml, cluster/core/networking/ingress-public/helm-release.yaml
It still doesn't work right. Maybe this will fix it?
**Benefits**
- fixes #
=> fix: ingressclass infighting

.sops.yaml, cluster/config/cluster-secrets.sops.yaml, cluster/core/flux-system/notifications/github/secret.sops.yaml, cluster/core/flux-system/webhooks/github/secret.sops.yaml, cluster/core/networking/cert-manager/cert-manager-secret.sops.yaml, cluster/core/networking/external-dns/external-dns-secret.sops.yaml, terraform/cloudflare/secret.sops.yaml, terraform/minio/secret.sops.yaml, tmpl/cluster/cluster-secrets.sops.yaml, tmpl/cluster/flux-system/webhooks/github/secret.sops.yaml
Use age instead of gpg. Re-encrypt secrets
**Benefits**
No more gpg!
Don't loose your key now..
- fixes #11
=> re-encrypt files with age

cluster/flux/apps.yaml, cluster/flux/config.yaml, cluster/flux/core.yaml, cluster/flux/flux-system/flux-cluster.yaml, tmpl/cluster/flux-cluster.yaml
Forgot to switch kustomizations too..
=> switch kustomizations to age as well v2

ansible/proxmox/inventory/group_vars/all/nginx-secrets.sops.yaml, ansible/proxmox/playbooks/files/nginx-override.conf, ansible/proxmox/playbooks/templates/proxmox.conf.j2, ansible/unifi/ansible.cfg, ansible/unifi/inventory/group_vars/all/nginx-secrets.sops.yaml, ansible/unifi/inventory/hosts.yml, ansible/unifi/playbooks/roles/acmesh/defaults/main.yml, ansible/unifi/playbooks/roles/acmesh/meta/main.yml, ansible/unifi/playbooks/roles/acmesh/tasks/main.yml, ansible/unifi/playbooks/tasks/mongo.yml, ansible/unifi/playbooks/tasks/nginx.yml, ansible/unifi/playbooks/tasks/packages.yml, ansible/unifi/playbooks/tasks/unifi.yml, ansible/unifi/playbooks/templates/unifi.conf.j2, ansible/unifi/playbooks/unifi-setup.yml, ansible/unifi/requirements.yml, cluster/apps/reverse-proxy/helm-release.yaml, terraform/proxmox/unifi.tf
=> feat: unifi

cluster/apps/media/prowlarr/helm-release.yaml, cluster/apps/media/radarr/helm-release.yaml, cluster/apps/media/readarr/helm-release.yaml, cluster/apps/media/sonarr/helm-release.yaml, cluster/apps/media/transmission/helm-release.yaml, terraform/authentik/.terraform.lock.hcl, terraform/authentik/applications.tf, terraform/authentik/customization.tf, terraform/authentik/directory.tf, terraform/authentik/flows.tf, terraform/authentik/main.tf, terraform/authentik/secret.sops.yaml, terraform/authentik/stages-prompt_fields.tf, terraform/authentik/stages.tf, terraform/authentik/system.tf
Setup authentik for media apps
**Benefits**
Proper auth, now accessible from wherever (again)
- fixes #7 
Nextcloud will come later
=> feat: authentik secured

cluster/apps/kustomization.yaml, cluster/apps/monitoring/kustomization.yaml, cluster/apps/monitoring/uptime-kuma/data-pvc.yaml, cluster/apps/monitoring/uptime-kuma/helm-release.yaml, cluster/apps/monitoring/uptime-kuma/kustomization.yaml, terraform/authentik/applications.tf, terraform/authentik/customization.tf, terraform/authentik/directory.tf
Public statuspage-like monitoring
**Benefits**
Cool uptime graphs and notifications
**Fixes**
#102
=> feat: uptime kuma

cluster/apps/monitoring/weave-gitops/helm-release.yaml, cluster/apps/monitoring/weave-gitops/kustomization.yaml, cluster/apps/monitoring/weave-gitops/secret.sops.yaml, cluster/charts/kustomization.yaml, cluster/charts/weave-gitops-charts.yaml
For observability
**Benefits**
- fixes #102 
=> feat: add weave-gitops

.taskfiles/AuthentikTasks.yml, .taskfiles/TerraformTasks.yml, Taskfile.yml, terraform/cloudflare/.terraform.lock.hcl, terraform/minio/.terraform.lock.hcl
=> feat: cleanup terraform taskfiles

cluster/apps/nextcloud/helm-release.yaml
Faster php in nextcloud
**Benefits**
- fixes #
=> feat: optimize nextcloud

cluster/config/cluster-secrets.sops.yaml, cluster/core/flux-system/notifications/kustomization.yaml, cluster/core/flux-system/notifications/telegram/notification.yaml, cluster/core/flux-system/notifications/telegram/secret.sops.yaml
Add telegram notifications from flux
=> feat(flux): Add telegram notifications

cluster/charts/democratic-csi-charts.yaml, cluster/charts/kustomization.yaml, cluster/core/storage/democratic-csi/kustomization.yaml, cluster/core/storage/democratic-csi/nfs/helm-release.yaml, cluster/core/storage/democratic-csi/nfs/kustomization.yaml, cluster/core/storage/democratic-csi/nfs/truenas-secret.sops.yaml
Turns out truenas-csp doesn't do NFS. We need something for that
**Benefits**
Some apps need RWX volumes
- fixes #
=> feat: democratic-csi

cluster/apps/kube-system/kured/helm-release.yaml, cluster/apps/kube-system/metrics-server/helm-release.yaml, cluster/apps/kube-system/reloader/helm-release.yaml, cluster/apps/nextcloud/helm-release.yaml, cluster/apps/nextcloud/secrets.sops.yaml
=> feat(monitoring) add servicemonitors for some stuff

cluster/core/flux-system/kustomization.yaml, cluster/core/flux-system/monitoring/kustomization.yaml, cluster/core/flux-system/monitoring/podmonitor.yaml, cluster/core/flux-system/monitoring/prometheusrule.yaml
=> feat(monitoring): steal flux monitoring

cluster/core/networking/cert-manager/helm-release.yaml, cluster/core/networking/cert-manager/prometheusrule.yaml, cluster/core/networking/external-dns/helm-release.yaml, cluster/core/networking/ingress-private/helm-release.yaml, cluster/core/networking/ingress-public/helm-release.yaml, cluster/core/networking/k8s-gateway/helm-release.yaml, cluster/core/networking/metallb/helm-release.yaml, cluster/core/storage/snapshot-controller/helm-release.yaml, cluster/core/storage/velero/helm-release.yaml
=> feat(monitoring) add more monitoring

cluster/apps/monitoring/grafana/grafana-secrets.sops.yaml, cluster/apps/monitoring/grafana/helm-release.yaml, cluster/apps/monitoring/grafana/kustomization.yaml, cluster/apps/monitoring/kube-prometheus-stack/helm-release.yaml, cluster/apps/monitoring/kustomization.yaml, cluster/apps/monitoring/thanos/helm-release.yaml, cluster/charts/grafana-charts.yaml, cluster/charts/kustomization.yaml, terraform/authentik/applications.tf, terraform/authentik/customization.tf, terraform/authentik/directory.tf, terraform/authentik/secret.sops.yaml
=> feat(monitoring): grafana

.taskfiles/AnsibleTasks.yml, ansible/inventory/group_vars/all/node-exporter.yml, ansible/inventory/group_vars/proxmox/proxmox-secrets.sops.yaml, ansible/playbooks/bastion-setup.yml, ansible/playbooks/files/pve-exporter.service, ansible/playbooks/proxmox-setup.yml, ansible/playbooks/templates/pve-exporter.yaml.j2, ansible/requirements.yml, cluster/apps/monitoring/kube-prometheus-stack/helm-release.yaml
=> feat(monitoring): external node exporters

cluster/apps/monitoring/kustomization.yaml, cluster/apps/monitoring/unpoller/helm-release.yaml, cluster/apps/monitoring/unpoller/kustomization.yaml, cluster/apps/monitoring/unpoller/unifi-secrets.sops.yaml
=> feat(monitoring): unpoller

.github/linters/.markdownlint.yaml, README.md
Elaborate on what this is all about
**Benefits**
Some people will be happy
Exposes how dumb i am
- fixes #167
=> Improve the Readme

terraform/authentik/applications.tf, terraform/authentik/customization.tf, terraform/authentik/secret.sops.yaml
Setup pve+authentik oidc
**Benefits**
One less login in 1password
- fixes #
=> feat(security) Setup proxmox OIDC

cluster/apps/database/cloudnative-pg/clusters/kustomization.yaml, cluster/apps/database/cloudnative-pg/clusters/loadbalancer.yaml, cluster/apps/database/cloudnative-pg/clusters/postgres-cluster.yaml, cluster/apps/database/cloudnative-pg/clusters/scheduledbackup.yaml, cluster/apps/database/cloudnative-pg/clusters/secrets.sops.yaml, cluster/apps/database/cloudnative-pg/helm-release.yaml, cluster/apps/database/cloudnative-pg/kustomization.yaml, cluster/apps/database/kustomization.yaml, cluster/apps/database/redis/helm-release.yaml, cluster/apps/database/redis/kustomization.yaml, cluster/apps/database/redis/redis-secret.sops.yaml, cluster/apps/kustomization.yaml, cluster/charts/cloudnative-pg-charts.yaml, cluster/core/namespaces/database.yaml, cluster/core/namespaces/kustomization.yaml, terraform/minio/postgres.tf, terraform/minio/secret.sops.yaml
Add global postgres and redis for apps
**Benefits**
One DB to rule them all
- fixes #
=> feat: databases

cluster/core/security/external-secrets/helm-release.yaml, cluster/core/security/external-secrets/kustomization.yaml, cluster/core/security/kustomization.yaml, cluster/core/security/onepassword-connect/clustersecretstore.yaml, cluster/core/security/onepassword-connect/helmrelease.yaml, cluster/core/security/onepassword-connect/kustomization.yaml, cluster/core/security/onepassword-connect/onepassword-connect-secret.sops.yaml, cluster/crds/external-secrets/crds.yaml, cluster/crds/external-secrets/kustomization.yaml
Adds external-secrets and onepassword-connect
**Benefits**
It ain't vault, but i pay for it anyway, might as well and not duplicate secrets over many files
- fixes #
=> feat(security): Add external-secrets and onepassword-connect

cluster/apps/database/cloudnative-pg/clusters/external-secret.yaml, cluster/apps/database/cloudnative-pg/clusters/postgres-v1-cluster.yaml, cluster/apps/security/authentik/external-secrets.yaml, cluster/apps/security/authentik/helm-release.yaml, cluster/apps/security/authentik/kustomization.yaml
=> chore: switch authnetik to cloudnative-pg and externalSecrets

cluster/apps/database/ext-postgres-operator/helm-release.yaml, cluster/apps/database/ext-postgres-operator/kustomization.yaml, cluster/charts/ext-postgres-operator-charts.yaml, cluster/charts/kustomization.yaml, cluster/crds/ext-postgres-operator/crds.yaml, cluster/crds/ext-postgres-operator/kustomization.yaml, cluster/crds/kustomization.yaml
Add ext-postgres-operator
**Benefits**/
cpng can't do dynamic provisioning. Therefore add 
- fixes #
=> feat(database): postgres operator

cluster/apps/media/prowlarr/helm-release.yaml, cluster/apps/media/prowlarr/kustomization.yaml, cluster/apps/media/radarr/helm-release.yaml, cluster/apps/media/readarr/helm-release.yaml, cluster/apps/media/sonarr/helm-release.yaml, cluster/apps/media/transmission/helm-release.yaml
Move out of iscsi for media apps
**Benefits**
Slowly getting rid of iscsi
- fixes #
=> feat(media): move media apps to nvmeof

cluster/apps/database/cloudnative-pg/clusters/external-secret.yaml, cluster/apps/security/authentik/external-secrets.yaml, cluster/apps/security/authentik/helm-release.yaml
Cleanup external secrets naming schemes
**Benefits**
- fixes #
=> chore: cleanup external secrets inconsistencies

cluster/apps/monitoring/goldilocks/helm-release.yaml, cluster/apps/monitoring/goldilocks/kustomization.yaml, cluster/apps/monitoring/kustomization.yaml, cluster/apps/monitoring/vpa/helm-release.yaml, cluster/apps/monitoring/vpa/kustomization.yaml, cluster/charts/fairwinds-charts.yaml, cluster/charts/kustomization.yaml
=> feat(monitoring): Add vpa&goldilocks

cluster/apps/database/redis/helm-release.yaml, cluster/apps/database/redis/kustomization.yaml, cluster/apps/media/kustomization.yaml, cluster/apps/media/nitter/configmap.yaml, cluster/apps/media/nitter/helm-release.yaml, cluster/apps/media/nitter/kustomization.yaml, cluster/config/cluster-secrets.sops.yaml
=> feat(media): Add nitter

cluster/apps/kustomization.yaml, cluster/apps/networking/kustomization.yaml, cluster/apps/networking/speedtest-go/external-secret.yaml, cluster/apps/networking/speedtest-go/helm-release.yaml, cluster/apps/networking/speedtest-go/kustomization.yaml
Devin got us a nice image, let's use it
**Benefits**
- fixes #
=> feat(networking): Add speedtest-go

cluster/apps/monitoring/kustomization.yaml, cluster/apps/monitoring/loki/datasource.yaml, cluster/apps/monitoring/loki/externalsecret.yaml, cluster/apps/monitoring/loki/helm-release.yaml, cluster/apps/monitoring/loki/helmrelease.yaml, cluster/apps/monitoring/loki/kustomization.yaml, cluster/apps/monitoring/loki/prometheusrule.yaml, cluster/apps/monitoring/loki/servicemonitor.yaml, terraform/minio/.terraform.lock.hcl, terraform/minio/loki.tf, terraform/minio/secret.sops.yaml
For logging and stuff
**Benefits**
- fixes #
=> feat(monitoring): loki

cluster/apps/monitoring/kustomization.yaml, cluster/apps/monitoring/vector/agent/helmrelease.yaml, cluster/apps/monitoring/vector/agent/kustomization.yaml, cluster/apps/monitoring/vector/aggregator/helmrelease.yaml, cluster/apps/monitoring/vector/aggregator/kustomization.yaml, cluster/apps/monitoring/vector/kustomization.yaml, cluster/charts/vector-charts.yaml, cluster/core/networking/ingress-private/helm-release.yaml, cluster/core/networking/ingress-public/helm-release.yaml
Collect and ship logs to loki
**Benefits**
- fixes #
=> feat(monitoring): vector

cluster/apps/monitoring/thanos/helm-release.yaml, terraform/minio/.terraform.lock.hcl, terraform/minio/k3s.tf, terraform/minio/loki.tf, terraform/minio/main.tf, terraform/minio/modules/minio/main.tf, terraform/minio/modules/minio/variables.tf, terraform/minio/nextcloud.tf, terraform/minio/postgres.tf, terraform/minio/thanos.tf, terraform/minio/volsync.tf
Cleanup minio terraform code
**Benefits**
No sops, no repeating code
- fixes #
=> chore: minio terraform external secrets

cluster/apps/kube-system/kyverno/clusterrolebinding.yaml, cluster/apps/kube-system/kyverno/helmrelease.yaml, cluster/apps/kube-system/kyverno/kustomization.yaml, cluster/charts/kustomization.yaml, cluster/charts/kyverno-charts.yaml, cluster/crds/cloudnative-pg/crds.yaml, cluster/crds/external-secrets/crds.yaml, cluster/crds/kyverno/crds.yaml, cluster/crds/kyverno/kustomization.yaml, cluster/crds/prometheus-operator/crds.yaml, cluster/crds/snapshot-controller/crds.yaml
Add kyverno
**Benefits**
This will automate adding those stupid repeating annotations everywhere
- fixes #
=> feat(system): kyverno

cluster/apps/default/hajimari/helmrelease.yaml, cluster/apps/default/s3-static-proxy/helmrelease.yaml, cluster/apps/fileservers/immich/web/helmrelease.yaml, cluster/apps/games/minecraft/helmrelease.yaml, cluster/apps/media/prowlarr/helmrelease.yaml, cluster/apps/media/radarr/helmrelease.yaml, cluster/apps/media/sonarr/helmrelease.yaml, cluster/apps/media/transmission/helmrelease.yaml, cluster/apps/monitoring/goldilocks/helmrelease.yaml, cluster/apps/monitoring/grafana/helmrelease.yaml, cluster/apps/monitoring/kube-prometheus-stack/helmrelease.yaml, cluster/apps/monitoring/loki/helmrelease.yaml, cluster/apps/monitoring/thanos/helmrelease.yaml, cluster/apps/monitoring/uptime-kuma/helmrelease.yaml, cluster/apps/nextcloud/helmrelease.yaml, cluster/apps/reverse-proxy/helmrelease.yaml, cluster/apps/security/authentik/helmrelease.yaml, cluster/core/flux-system/webhooks/github/ingress.yaml, cluster/core/networking/cert-manager/clusterpolicy.yaml, cluster/core/security/onepassword-connect/helmrelease.yaml
Use kyverno
**Benefits**
- fixes #
=> chore: kyverno annotations

cluster/apps/fileservers/immich/configmap.yaml, cluster/apps/fileservers/immich/externalsecret.yaml, cluster/apps/fileservers/immich/redis/helmrelease.yaml, cluster/apps/fileservers/immich/redis/kustomization.yaml, cluster/apps/fileservers/immich/redis/pvc.yaml, cluster/apps/fileservers/immich/server/helmrelease.yaml
Shared redis has some fundamental problems, we have to revert again :/
**Benefits**
- fixes #
=> fix(immich)fix immich redis

cluster/apps/security/authentik/helmrelease.yaml, cluster/apps/security/authentik/pvc.yaml
Add a media and templates pvc to authentik
**Benefits**
Should allow to upload avatars
It's a PVC..
- fixes #
=> feat(security): Add media pvc to authentik

cluster/apps/fileservers/nextcloud/helmrelease.yaml, cluster/apps/kube-system/kured/helmrelease.yaml, cluster/apps/kube-system/metrics-server/helmrelease.yaml, cluster/apps/kube-system/reloader/helmrelease.yaml, cluster/apps/monitoring/grafana/helmrelease.yaml, cluster/apps/monitoring/thanos/helmrelease.yaml, cluster/core/networking/external-dns/helmrelease.yaml, cluster/core/networking/k8s-gateway/helmrelease.yaml, cluster/core/networking/metallb/helmrelease.yaml
Disable monitors we don't handle 
**Benefits**
- fixes #
=> disable useless monitoring

cluster/apps/fileservers/immich/configmap.yaml, cluster/apps/fileservers/immich/kustomization.yaml
Right now the ML part of immich is very unstable, with pods that crash. This affects other tasks, and the ML functionality isn't even that usefull right now. Disable it
**Benefits**
- fixes #
=> fix: Disable ML in immich

cluster/apps/fileservers/tandoor/configmap.yaml, cluster/apps/fileservers/tandoor/externalsecret.yaml, cluster/apps/fileservers/tandoor/helmrelease.yaml, cluster/apps/fileservers/tandoor/kustomization.yaml, cluster/apps/fileservers/tandoor/pvc.yaml, terraform/authentik/applications.tf, terraform/authentik/customization.tf, terraform/authentik/secret.sops.yaml
For recipies and stuff
**Benefits**
- fixes #
=> feat: tandoor

cluster/apps/fileservers/paperless/externalsecret.yaml, cluster/apps/fileservers/paperless/helmrelease.yaml, cluster/apps/fileservers/paperless/kustomization.yaml, cluster/apps/fileservers/paperless/pvc.yaml
For storing documents
**Benefits**
- fixes #
=> feat: add paperless-ngx

kubernetes/apps/kube-system/cilium/app/helm-release.yaml, kubernetes/apps/monitor/grafana/app/externalsecret.yaml, kubernetes/apps/monitor/grafana/app/helmrelease.yaml, kubernetes/apps/monitor/grafana/app/kustomization.yaml, kubernetes/apps/monitor/grafana/ks.yaml, kubernetes/apps/monitor/kube-prometheus-stack/app/externalsecret.yaml, kubernetes/apps/monitor/kube-prometheus-stack/app/helmrelease.yaml, kubernetes/apps/monitor/kube-prometheus-stack/app/kustomization.yaml, kubernetes/apps/monitor/kube-prometheus-stack/ks.yaml, kubernetes/apps/monitor/kustomization.yaml, kubernetes/apps/monitor/namespace.yaml, kubernetes/apps/monitor/speedtest-exporter/app/helmrelease.yaml, kubernetes/apps/monitor/speedtest-exporter/app/kustomization.yaml, kubernetes/apps/monitor/speedtest-exporter/ks.yaml, kubernetes/apps/monitor/thanos/app/thanos/helmrelease.yaml, kubernetes/apps/monitor/thanos/app/thanos/kustomization.yaml, kubernetes/apps/monitor/thanos/ks.yaml, kubernetes/apps/monitor/unifi-poller/app/externalsecret.yaml, kubernetes/apps/monitor/unifi-poller/app/helmrelease.yaml, kubernetes/apps/monitor/unifi-poller/app/kustomization.yaml, kubernetes/apps/monitor/unifi-poller/ks.yaml, kubernetes/apps/network/ingress-nginx/private/helmrelease.yaml, kubernetes/apps/network/ingress-nginx/public/helmrelease.yaml, kubernetes/apps/security/external-secrets/app/helmrelease.yaml, kubernetes/flux/repositories/helm/grafana.yaml, kubernetes/flux/repositories/helm/kustomization.yaml, kubernetes/flux/repositories/helm/prometheus-community.yaml
=> Feat: talos monitoring

kubernetes/apps/fileserver/immich/app/typesense/externalsecret.yaml, kubernetes/apps/fileserver/immich/app/typesense/kustomization.yaml, kubernetes/apps/fileserver/nextcloud/app/externalsecret.yaml, kubernetes/apps/fileserver/nextcloud/app/kustomization.yaml, kubernetes/apps/fileserver/nextcloud/ks.yaml, kubernetes/apps/fileserver/paperless/app/externalsecret.yaml, kubernetes/apps/fileserver/paperless/app/kustomization.yaml, kubernetes/apps/fileserver/paperless/app/replicationdestination.yaml, kubernetes/apps/fileserver/paperless/app/replicationsource.yaml, kubernetes/apps/fileserver/paperless/ks.yaml, kubernetes/apps/fileserver/tandoor/app/externalsecret.yaml, kubernetes/apps/fileserver/tandoor/app/kustomization.yaml, kubernetes/apps/fileserver/tandoor/ks.yaml, kubernetes/apps/games/minecraft/app/externalsecret.yaml, kubernetes/apps/games/minecraft/app/replicationdestination.yaml, kubernetes/apps/games/minecraft/app/replicationsource.yaml, kubernetes/apps/games/minecraft/ks.yaml, kubernetes/apps/games/namespace.yaml, kubernetes/apps/media/prowlarr/app/externalsecret.yaml, kubernetes/apps/media/prowlarr/app/kustomization.yaml, kubernetes/apps/media/prowlarr/ks.yaml, kubernetes/apps/media/radarr/app/externalsecret.yaml, kubernetes/apps/media/radarr/app/kustomization.yaml, kubernetes/apps/media/radarr/ks.yaml, kubernetes/apps/media/sonarr/app/externalsecret.yaml, kubernetes/apps/media/sonarr/app/kustomization.yaml, kubernetes/apps/media/sonarr/ks.yaml
Re-enable restic backups everywhere
**Benefits**
- fixes #
=> chore: Enable backups

talos/talconfig.yaml, talos/talenv.sops.yaml, talos/talenv.yaml, talos/update-config.sh
Upgrade talos
**Benefits**
- fixes #
=> Chore/talos 1.4.6

kubernetes/apps/flux-system/tf-controller/app/externalsecret.yaml, kubernetes/apps/flux-system/tf-controller/app/helmrelease.yaml, kubernetes/apps/flux-system/tf-controller/app/kustomization.yaml, kubernetes/apps/flux-system/tf-controller/ks.yaml, kubernetes/apps/flux-system/weave-gitops/app/helmrelease.yaml, kubernetes/flux/config/flux.yaml, kubernetes/flux/repositories/helm/kustomization.yaml, kubernetes/flux/repositories/helm/weaveworks.yaml
We should be doing this the gitops way finally
**Benefits**
- fixes #
=> feat: tf-controller

kubernetes/apps/database/redis/app/helmrelease.yaml, kubernetes/apps/database/redis/app/kustomization.yaml, kubernetes/apps/database/redis/ks.yaml
3rd try into having a HA-ready redis
**Benefits**
- fixes #
=> feat: Add redis-ha

kubernetes/apps/fileserver/immich/app/externalsecret.yaml, kubernetes/apps/fileserver/immich/app/server/helmrelease.yaml, kubernetes/apps/fileserver/nextcloud/app/externalsecret.yaml, kubernetes/apps/fileserver/nextcloud/app/helmrelease.yaml, kubernetes/apps/fileserver/paperless/app/externalsecret.yaml, kubernetes/apps/fileserver/paperless/app/helmrelease.yaml, kubernetes/apps/fileserver/tandoor/app/externalsecret.yaml, kubernetes/apps/fileserver/tandoor/app/helmrelease.yaml, kubernetes/apps/security/authentik/app/externalsecret.yaml, kubernetes/apps/security/authentik/app/helmrelease.yaml
=> chore: switch over to postgres-init

.pre-commit-config.yaml, kubernetes/apps/monitor/gatus/app/config/config.yaml, kubernetes/apps/monitor/gatus/app/externalsecret.yaml, kubernetes/apps/monitor/gatus/app/helmrelease.yaml, kubernetes/apps/monitor/gatus/app/kustomization.yaml, kubernetes/apps/monitor/gatus/app/rbac.yaml, kubernetes/apps/monitor/gatus/ks.yaml, kubernetes/apps/monitor/kustomization.yaml
=> feat: gatus

kubernetes/apps/monitor/connectbox-exporter/app/externalsecret.yaml, kubernetes/apps/monitor/connectbox-exporter/app/helmrelease.yaml, kubernetes/apps/monitor/connectbox-exporter/app/kustomization.yaml, kubernetes/apps/monitor/connectbox-exporter/ks.yaml
For monitoring what UPC does
**Benefits**
- fixes #
=> feat: Add conntectbox-exporter

kubernetes/apps/media/prowlarr/app/externalsecret.yaml, kubernetes/apps/media/prowlarr/app/helmrelease.yaml, kubernetes/apps/media/radarr/app/externalsecret.yaml, kubernetes/apps/media/radarr/app/helmrelease.yaml
No more sqlite!
**Benefits**
- fixes #
=> feat: Move compatible arrs to postgres

kubernetes/apps/kube-system/intel-device-plugin/app/exporter/helmrelease.yaml, kubernetes/apps/kube-system/intel-device-plugin/app/exporter/kustomization.yaml, kubernetes/apps/kube-system/intel-device-plugin/app/gpu/helmrelease.yaml, kubernetes/apps/kube-system/intel-device-plugin/app/gpu/kustomization.yaml, kubernetes/apps/kube-system/intel-device-plugin/app/kustomization.yaml, kubernetes/apps/kube-system/intel-device-plugin/app/operator/helmrelease.yaml, kubernetes/apps/kube-system/intel-device-plugin/app/operator/kustomization.yaml, kubernetes/apps/kube-system/intel-device-plugin/ks.yaml, kubernetes/apps/kube-system/kustomization.yaml, kubernetes/apps/kube-system/node-feature-discovery/app/helmrelease.yaml, kubernetes/apps/kube-system/node-feature-discovery/app/kustomization.yaml, kubernetes/apps/kube-system/node-feature-discovery/ks.yaml, kubernetes/flux/repositories/helm/intel.yaml, kubernetes/flux/repositories/helm/kustomization.yaml, kubernetes/flux/repositories/helm/node-feature-discovery.yaml
Now that we have gvtd, install the appropriate kube plugins so that pods can utilize it in the future (immich)
**Benefits**
- fixes #
=> feat: intel gpu plugins

infrastructure/terraform/authentik/applications.tf, infrastructure/terraform/authentik/customization.tf, infrastructure/terraform/authentik/oauth2_application/main.tf, infrastructure/terraform/authentik/oauth2_application/variables.tf, infrastructure/terraform/authentik/proxy_application/main.tf, infrastructure/terraform/authentik/proxy_application/outputs.tf, infrastructure/terraform/authentik/proxy_application/variables.tf, infrastructure/terraform/authentik/system.tf, kubernetes/apps/fileserver/tandoor/app/externalsecret.yaml
Modularize authentik code a bit
**Benefits**
Less repeating lines
- fixes #
=> Feat: authentik tf module

infrastructure/terraform/authentik/.terraform.lock.hcl, infrastructure/terraform/authentik/applications.tf, infrastructure/terraform/authentik/main.tf, infrastructure/terraform/authentik/oauth2_application/main.tf, kubernetes/apps/fileserver/nextcloud/app/externalsecret.yaml, kubernetes/apps/fileserver/tandoor/app/externalsecret.yaml, kubernetes/apps/monitor/grafana/app/externalsecret.yaml
Store all secrets in 1password for authentik
**Benefits**
Single source of truth
1password must be running
- fixes #
=> Feat: authentik tf 1password

kubernetes/apps/flux-system/tf-controller/ks.yaml, kubernetes/apps/flux-system/tf-controller/terraforms/authentik.yaml, kubernetes/apps/flux-system/tf-controller/terraforms/gitrepository.yaml, kubernetes/apps/flux-system/tf-controller/terraforms/kustomization.yaml, kubernetes/apps/flux-system/tf-controller/terraforms/minio.yaml
Add terraforms for running in tf-controller
**Benefits**
- fixes #
=> feat: add terraforms

kubernetes/apps/security/vaultwarden/app/externalsecret.yaml, kubernetes/apps/security/vaultwarden/app/helmrelease.yaml, kubernetes/apps/security/vaultwarden/app/kustomization.yaml, kubernetes/apps/security/vaultwarden/app/pvc.yaml, kubernetes/apps/security/vaultwarden/ks.yaml
Let's try out vaultwarden
**Benefits**
Choices!
- fixes #
=> feat: Give vaultwarden a spin

infrastructure/talos/talconfig.yaml, infrastructure/terraform/minio/modules/minio/main.tf, infrastructure/terraform/minio/modules/minio/outputs.tf, infrastructure/terraform/minio/modules/minio/variables.tf, infrastructure/terraform/minio/talos.tf, kubernetes/apps/talos-system/kustomization.yaml, kubernetes/apps/talos-system/namespace.yaml, kubernetes/apps/talos-system/talos-backup/app/cronjob.yaml, kubernetes/apps/talos-system/talos-backup/app/externalsecret.yaml, kubernetes/apps/talos-system/talos-backup/app/kustomization.yaml, kubernetes/apps/talos-system/talos-backup/app/serviceaccount.yaml, kubernetes/apps/talos-system/talos-backup/ks.yaml
Backup the talos cluster etcd periodically
**Benefits**
- fixes #
=> Feat: talos backups

kubernetes/apps/storage/democratic-csi/iscsi/externalsecret.yaml, kubernetes/apps/storage/democratic-csi/iscsi/helmrelease.yaml, kubernetes/apps/storage/democratic-csi/iscsi/kustomization.yaml, kubernetes/apps/storage/democratic-csi/ks.yaml, kubernetes/apps/storage/namespace.yaml
Because Travis wants some comparative benchmarks
**Benefits**
- fixes #
=> feat: Add iscsi

infrastructure/terraform/authentik/applications.tf, kubernetes/apps/media/kustomization.yaml, kubernetes/apps/media/lidarr/app/externalsecret.yaml, kubernetes/apps/media/lidarr/app/helmrelease.yaml, kubernetes/apps/media/lidarr/app/kustomization.yaml, kubernetes/apps/media/lidarr/ks.yaml
Go back to managing music collection
**Benefits**
- fixes #
=> Feat: lidarr

kubernetes/apps/media/kustomization.yaml, kubernetes/apps/media/navidrome/app/externalsecret.yaml, kubernetes/apps/media/navidrome/app/helmrelease.yaml, kubernetes/apps/media/navidrome/app/kustomization.yaml, kubernetes/apps/media/navidrome/app/replicationdestination.yaml, kubernetes/apps/media/navidrome/app/replicationsource.yaml, kubernetes/apps/media/navidrome/ks.yaml
For remote music playing enjoyment
**Benefits**
- fixes #
=> feat: Add navidrome

kubernetes/apps/media/kustomization.yaml, kubernetes/apps/media/recyclarr/app/configs/recyclarr.yml, kubernetes/apps/media/recyclarr/app/externalsecret.yaml, kubernetes/apps/media/recyclarr/app/helmrelease.yaml, kubernetes/apps/media/recyclarr/app/kustomization.yaml, kubernetes/apps/media/recyclarr/ks.yaml
I've no idea how this works yet, but we'll figure it out
**Benefits**
- fixes #
=> feat: add recyclarr

infrastructure/terraform/unifi/.terraform.lock.hcl, infrastructure/terraform/unifi/ap_groups.tf, infrastructure/terraform/unifi/firewall_group.tf, infrastructure/terraform/unifi/firewall_rule.tf, infrastructure/terraform/unifi/main.tf, infrastructure/terraform/unifi/networks.tf, infrastructure/terraform/unifi/port_forward.tf, infrastructure/terraform/unifi/user_groups.tf, infrastructure/terraform/unifi/vars.tf, infrastructure/terraform/unifi/wifi.tf
Unifi code
**Benefits**
- fixes #
=> feat: tf-unifi

kubernetes/apps/fileserver/n8n/app/externalsecret.yaml, kubernetes/apps/fileserver/n8n/app/helmrelease.yaml, kubernetes/apps/fileserver/n8n/app/kustomization.yaml, kubernetes/apps/fileserver/n8n/app/pvc.yaml, kubernetes/apps/fileserver/n8n/app/replicationsource.yaml, kubernetes/apps/fileserver/n8n/ks.yaml
Try out n8n
**Benefits**
- fixes #
=> feat: add n8n

kubernetes/apps/kyverno/kyverno/policies/ingress-external-dns-annotation.yaml
Fix for kyverno ingress policy typo.
=> Found this 's' you dropped

infrastructure/terraform/authentik/main.tf, infrastructure/terraform/cloudflare/main.tf, infrastructure/terraform/minio/main.tf, infrastructure/terraform/proxmox/main.tf, infrastructure/terraform/proxmox/talos-node/instance.tf, infrastructure/terraform/proxmox/talos-node/variables.tf, infrastructure/terraform/unifi/main.tf
=> chore: migrate from old backend to tf cloud

infrastructure/terraform/authentik/applications.tf, infrastructure/terraform/authentik/system.tf, kubernetes/apps/media/bazarr/app/externalsecret.yaml, kubernetes/apps/media/bazarr/app/helmrelease.yaml, kubernetes/apps/media/bazarr/app/kustomization.yaml, kubernetes/apps/media/bazarr/ks.yaml, kubernetes/apps/media/kustomization.yaml
=> feat: add bazarr

kubernetes/apps/selfhosted/paperless/app/externalsecret.yaml, kubernetes/apps/selfhosted/paperless/app/helmrelease.yaml, kubernetes/apps/selfhosted/paperless/app/kustomization.yaml, kubernetes/apps/selfhosted/paperless/app/pvc.yaml, kubernetes/apps/selfhosted/paperless/app/replicationdestination.yaml, kubernetes/apps/selfhosted/paperless/app/replicationsource.yaml, kubernetes/apps/selfhosted/paperless/ks.yaml, kubernetes/apps/selfhosted/tandoor/app/configmap.yaml, kubernetes/apps/selfhosted/tandoor/app/externalsecret.yaml, kubernetes/apps/selfhosted/tandoor/app/helmrelease.yaml, kubernetes/apps/selfhosted/tandoor/app/kustomization.yaml, kubernetes/apps/selfhosted/tandoor/app/pvc.yaml, kubernetes/apps/selfhosted/tandoor/app/replicationdestination.yaml, kubernetes/apps/selfhosted/tandoor/app/replicationsource.yaml, kubernetes/apps/selfhosted/tandoor/ks.yaml
=> chore: move more apps to selfhosted

kubernetes/apps/media/audiobookshelf/app/externalsecret.yaml, kubernetes/apps/media/audiobookshelf/app/helmrelease.yaml, kubernetes/apps/media/audiobookshelf/app/kustomization.yaml, kubernetes/apps/media/audiobookshelf/app/pvc.yaml, kubernetes/apps/media/audiobookshelf/app/replicationdestination.yaml, kubernetes/apps/media/audiobookshelf/app/replicationsource.yaml, kubernetes/apps/media/audiobookshelf/ks.yaml
=> feat: add audiobookshelf

infrastructure/terraform/authentik/applications.tf, infrastructure/terraform/authentik/main.tf, kubernetes/apps/media/midarr/app/externalsecret.yaml, kubernetes/apps/media/midarr/app/helmrelease.yaml, kubernetes/apps/media/midarr/app/kustomization.yaml, kubernetes/apps/media/midarr/ks.yaml
Try out midarr
**Benefits**
- fixes #
=> feat: add midarr

kubernetes/apps/default/homepage/app/configmap.yaml, kubernetes/apps/default/homepage/app/externalsecret.yaml, kubernetes/apps/default/homepage/app/helmrelease.yaml, kubernetes/apps/default/homepage/app/kustomization.yaml, kubernetes/apps/default/homepage/app/rbac.yaml, kubernetes/apps/default/homepage/ks.yaml, kubernetes/apps/downloads/bazarr/app/helmrelease.yaml, kubernetes/apps/downloads/lidarr/app/helmrelease.yaml, kubernetes/apps/downloads/prowlarr/app/helmrelease.yaml, kubernetes/apps/downloads/radarr/app/helmrelease.yaml, kubernetes/apps/downloads/readarr/app/helmrelease.yaml, kubernetes/apps/downloads/sonarr/app/helmrelease.yaml, kubernetes/apps/downloads/transmission/app/helmrelease.yaml, kubernetes/apps/flux-system/tf-controller/terraforms/authentik.yaml, kubernetes/apps/flux-system/tf-controller/terraforms/cloudflare.yaml, kubernetes/apps/flux-system/tf-controller/terraforms/minio.yaml
Hajimari is kinda boring..
**Benefits**
- fixes #
=> feat: add homepage

kubernetes/truenas/apps/monitor/node-exporter/app/helmrelease.yaml
See if we can override the hostname
**Benefits**
- fixes #
=> fix: try setting the hostname

kubernetes/truenas/apps/storage/kustomization.yaml, kubernetes/truenas/apps/storage/zot/app/config/config.json, kubernetes/truenas/apps/storage/zot/app/helmrelease.yaml, kubernetes/truenas/apps/storage/zot/app/kustomization.yaml, kubernetes/truenas/apps/storage/zot/app/pvc.yaml, kubernetes/truenas/apps/storage/zot/ks.yaml
Deploy zot
**Benefits**
- fixes #
=> feat: deploy zot

kubernetes/talos/apps/storage/democratic-csi/nfs/externalsecret.yaml, kubernetes/talos/apps/storage/democratic-csi/nfs/helmrelease.yaml
Add an NFS driver for SSDs
**Benefits**
- fixes #1552 
=> feat: add nfs ssd storage class

kubernetes/talos/apps/downloads/bazarr/app/helmrelease.yaml, kubernetes/talos/apps/downloads/bazarr/app/kustomization.yaml, kubernetes/talos/apps/downloads/bazarr/app/pvc.yaml, kubernetes/talos/apps/downloads/lidarr/app/helmrelease.yaml, kubernetes/talos/apps/downloads/lidarr/app/kustomization.yaml, kubernetes/talos/apps/downloads/lidarr/app/pvc.yaml, kubernetes/talos/apps/downloads/prowlarr/app/helmrelease.yaml, kubernetes/talos/apps/downloads/radarr/app/helmrelease.yaml, kubernetes/talos/apps/downloads/radarr/app/kustomization.yaml, kubernetes/talos/apps/downloads/radarr/app/pvc.yaml, kubernetes/talos/apps/downloads/readarr/app/helmrelease.yaml, kubernetes/talos/apps/downloads/readarr/app/kustomization.yaml, kubernetes/talos/apps/downloads/readarr/app/pvc.yaml, kubernetes/talos/apps/downloads/recyclarr/app/helmrelease.yaml, kubernetes/talos/apps/downloads/sonarr/app/helmrelease.yaml, kubernetes/talos/apps/downloads/sonarr/app/kustomization.yaml, kubernetes/talos/apps/downloads/sonarr/app/pvc.yaml, kubernetes/talos/apps/downloads/transmission/app/helmrelease.yaml, kubernetes/talos/apps/downloads/transmission/app/kustomization.yaml, kubernetes/talos/apps/downloads/transmission/app/pvc.yaml
=> chore: move downloads NS to ssd nfs sc

kubernetes/truenas/apps/monitor/kustomization.yaml, kubernetes/truenas/apps/monitor/node-exporter/app/helmrelease.yaml
=> fix: fix nas node exporter

kubernetes/talos/apps/media/audiobookshelf/app/helmrelease.yaml, kubernetes/talos/apps/media/audiobookshelf/app/kustomization.yaml, kubernetes/talos/apps/media/audiobookshelf/ks.yaml, kubernetes/talos/templates/volsync/kustomization.yaml, kubernetes/talos/templates/volsync/minio/externalsecret.yaml, kubernetes/talos/templates/volsync/minio/kustomization.yaml, kubernetes/talos/templates/volsync/minio/replicationdestination.yaml, kubernetes/talos/templates/volsync/minio/replicationsource.yaml, kubernetes/talos/templates/volsync/pvc.yaml
Start templating out repeatable volsync stuff (and more)
**Benefits**
- fixes #
=> feat: use volsync templates

.github/renovate.json5, .github/renovate/grafanaDashboards.json5
=> feat: re-add grafana dashboards to renovate

infrastructure/talos/README.md, infrastructure/terraform/authentik/applications.tf, kubernetes/talos/apps/automation/n8n/ks.yaml, kubernetes/talos/apps/database/cloudnative-pg/cluster/loadbalancer.yaml, kubernetes/talos/apps/kube-system/cilium/app/helm-release.yaml, kubernetes/talos/apps/monitor/grafana/ks.yaml, kubernetes/talos/apps/monitor/kube-prometheus-stack/ks.yaml, kubernetes/talos/apps/security/external-secrets/ks.yaml, kubernetes/talos/apps/selfhosted/paperless/app/helmrelease.yaml, kubernetes/talos/apps/selfhosted/paperless/ks.yaml
=> chore: retire internal domain

kubernetes/talos/apps/monitor/thanos/app/thanos/externalsecret.yaml, kubernetes/talos/apps/monitor/thanos/app/thanos/helmrelease.yaml, kubernetes/talos/apps/monitor/thanos/app/thanos/kustomization.yaml
Switch over to a saner thanos chart
**Benefits**
- fixes #
=> chore: thanos new chart

kubernetes/talos/apps/security/external-secrets/op/onepassword/clustersecretstore.yaml, kubernetes/talos/apps/security/external-secrets/op/onepassword/helmrelease.yaml, kubernetes/talos/apps/security/external-secrets/op/onepassword/kustomization.yaml, kubernetes/truenas/apps/security/external-secrets/stores/onepassword/clustersecretstore.yaml, kubernetes/truenas/apps/security/external-secrets/stores/onepassword/helmrelease.yaml, kubernetes/truenas/apps/security/external-secrets/stores/onepassword/kustomization.yaml
Move stuff out of vyos
**Benefits**
- fixes #
=> chore: reintroduce in-cluster op

kubernetes/talos/apps/database/cloudnative-pg/cluster/cluster.yaml, kubernetes/talos/apps/database/cloudnative-pg/cluster/loadbalancer.yaml, kubernetes/talos/apps/kube-system/talos-backup/app/externalsecret.yaml, kubernetes/talos/apps/monitor/gatus/app/config/config.yaml, kubernetes/talos/apps/monitor/kube-prometheus-stack/addons/scrapeconfigs/minio.yaml, kubernetes/talos/apps/monitor/kube-prometheus-stack/addons/scrapeconfigs/node-exporter.yaml, kubernetes/talos/apps/monitor/kube-prometheus-stack/addons/scrapeconfigs/smartctl-exporter.yaml, kubernetes/talos/apps/monitor/kube-prometheus-stack/app/externalsecret.yaml, kubernetes/talos/apps/network/s3-proxy/app/configmap.yaml, kubernetes/talos/apps/selfhosted/nextcloud/app/helmrelease.yaml, kubernetes/talos/templates/volsync/minio/externalsecret.yaml, kubernetes/truenas/apps/media/mediamtx/ks.yaml, kubernetes/truenas/apps/monitor/node-exporter/app/helmrelease.yaml, kubernetes/truenas/apps/monitor/smartctl-exporter/app/helmrelease.yaml, kubernetes/truenas/apps/network/ingress-nginx/default-certificate/certificate.yaml, kubernetes/truenas/apps/storage/minio/ks.yaml
Abandon dedicated NAS domain
**Benefits**
- fixes #
=> feat: move from dedicated NAS domain

infrastructure/terraform/authentik/applications.tf, infrastructure/terraform/authentik/main.tf, infrastructure/terraform/authentik/oauth2_application/main.tf, infrastructure/terraform/authentik/oauth2_application/variables.tf, infrastructure/terraform/authentik/proxy_application/main.tf, kubernetes/talos/apps/media/kustomization.yaml, kubernetes/talos/apps/media/kyoo/app/configmap.yaml, kubernetes/talos/apps/media/kyoo/app/externalsecret.yaml, kubernetes/talos/apps/media/kyoo/app/helmrelease.yaml, kubernetes/talos/apps/media/kyoo/app/kustomization.yaml, kubernetes/talos/apps/media/kyoo/app/pvc.yaml, kubernetes/talos/apps/media/kyoo/ks.yaml
It may prove convienient. Kodi is still OG
**Benefits**
- fixes #
=> Feat: kyoo

kubernetes/talos/apps/database/ext-postgres-operator/app/externalsecret.yaml, kubernetes/talos/apps/database/ext-postgres-operator/app/helmrelease.yaml, kubernetes/talos/apps/database/ext-postgres-operator/app/kustomization.yaml, kubernetes/talos/apps/database/ext-postgres-operator/ks.yaml, kubernetes/talos/apps/database/kustomization.yaml, kubernetes/talos/flux/repositories/helm/kustomization.yaml, kubernetes/talos/flux/repositories/helm/movetokube.yaml
Add an operator for managing postgres users/db
**Benefits**
No more postgres-init kludge
- fixes #
=> feat: add ext-postgres-operator

kubernetes/talos/apps/media/kyoo/app/externalsecret.yaml, kubernetes/talos/apps/media/kyoo/app/helmrelease.yaml, kubernetes/talos/apps/media/kyoo/app/postgres.yaml
=> feat: try out pg operator on kyoo

kubernetes/truenas/apps/infra/haproxy/app/config/haproxy.cfg, kubernetes/truenas/apps/infra/haproxy/app/helmrelease.yaml, kubernetes/truenas/apps/infra/haproxy/app/kustomization.yaml, kubernetes/truenas/apps/infra/haproxy/ks.yaml, kubernetes/truenas/apps/infra/kustomization.yaml, kubernetes/truenas/apps/infra/namespace.yaml
Move the proxmox haproxy out of the router
=> feat: add haproxy

kubernetes/truenas/apps/infra/haproxy/app/config/haproxy.cfg, kubernetes/truenas/apps/infra/haproxy/app/helmrelease.yaml, kubernetes/truenas/apps/network/metallb/config/ipaddresspool.yaml
See if we can get away with this
=> feat: talos haproxy

kubernetes/talos/bootstrap/talos/talconfig.yaml, kubernetes/truenas/apps/infra/haproxy/app/helmrelease.yaml, kubernetes/truenas/apps/network/metallb/config/ipaddresspool.yaml, kubernetes/truenas/apps/network/metallb/config/l2advertisement.yaml
VIP is okay but we can still do haproxy
=> feat: switch talos to haproxy

kubernetes/talos/apps/selfhosted/actual/app/helmrelease.yaml, kubernetes/talos/apps/selfhosted/actual/app/kustomization.yaml, kubernetes/talos/apps/selfhosted/actual/ks.yaml
=> Feat: actual budget

kubernetes/talos/apps/actions-runner-system/actions-runner-controller/ks.yaml, kubernetes/talos/apps/actions-runner-system/actions-runner-controller/operator/externalsecret.yaml, kubernetes/talos/apps/actions-runner-system/actions-runner-controller/operator/helmrelease.yaml, kubernetes/talos/apps/actions-runner-system/actions-runner-controller/operator/kustomization.yaml, kubernetes/talos/apps/actions-runner-system/actions-runner-controller/runners/helmrelease.yaml, kubernetes/talos/apps/actions-runner-system/actions-runner-controller/runners/kustomization.yaml, kubernetes/talos/apps/actions-runner-system/actions-runner-controller/runners/rbac.yaml, kubernetes/talos/apps/actions-runner-system/kustomization.yaml, kubernetes/talos/apps/actions-runner-system/namespace.yaml, kubernetes/talos/flux/repositories/helm/actions-runner-controller.yaml, kubernetes/talos/flux/repositories/helm/kustomization.yaml
=> feat: add gha ooperator

kubernetes/talos/apps/selfhosted/kustomization.yaml, kubernetes/talos/apps/selfhosted/partdb/app/externalsecret.yaml, kubernetes/talos/apps/selfhosted/partdb/app/helmrelease.yaml, kubernetes/talos/apps/selfhosted/partdb/app/kustomization.yaml, kubernetes/talos/apps/selfhosted/partdb/ks.yaml
Install part-db
**Benefits**
For our electronic junk inventory needs
It's symfony..
- fixes #2890
=> Feat: part-db

kubernetes/talos/apps/default/kustomization.yaml, kubernetes/talos/components/namespace/kustomization.yaml, kubernetes/talos/components/namespace/namespace.yaml
=> feat: use namespace component

kubernetes/apps/kube-system/kustomization.yaml, kubernetes/apps/kube-system/system-upgrade/controller/helmrelease.yaml, kubernetes/apps/kube-system/system-upgrade/controller/kustomization.yaml, kubernetes/apps/kube-system/system-upgrade/controller/rbac.yaml, kubernetes/apps/kube-system/system-upgrade/ks.yaml, kubernetes/apps/kube-system/system-upgrade/plans/kubernetes.yaml, kubernetes/apps/kube-system/system-upgrade/plans/kustomization.yaml, kubernetes/apps/kube-system/system-upgrade/plans/talos.yaml
Looks like all the kinks are worked out
=> feat: re-introduce SUC

infrastructure/terraform/authentik/applications.tf, infrastructure/terraform/authentik/main.tf, kubernetes/apps/selfhosted/kustomization.yaml, kubernetes/apps/selfhosted/romm/app/externalsecret.yaml, kubernetes/apps/selfhosted/romm/app/helmrelease.yaml, kubernetes/apps/selfhosted/romm/app/kustomization.yaml, kubernetes/apps/selfhosted/romm/ks.yaml
=> feat: add romm
